// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'error': string;
  'statCard': string;
  'statLabel': string;
  'statValue': string;
  'statsContainer': string;
  'statsGrid': string;
}
declare var cssExports: CssExports;
export = cssExports;
