// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'empty': string;
  'list': string;
  'macroCard': string;
  'macroContent': string;
  'macroHeader': string;
}
declare var cssExports: CssExports;
export = cssExports;
