// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'composer': string;
  'composerContainer': string;
  'fileIcon': string;
  'filePreview': string;
  'fileUploadContainer': string;
  'handoffAssigned': string;
  'imagePreview': string;
  'inputRow': string;
  'macroItem': string;
  'macrosButton': string;
  'macrosListContainer': string;
  'macrosMenu': string;
  'macrosSearch': string;
  'progressBar': string;
  'progressContainer': string;
  'progressText': string;
  'removeFileButton': string;
  'selected': string;
  'sendButton': string;
  'shortcutDropdown': string;
  'shortcutItem': string;
  'shortcutKey': string;
  'shortcutListItem': string;
  'shortcutValue': string;
  'uploadButton': string;
  'uploadingState': string;
}
declare var cssExports: CssExports;
export = cssExports;
