// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'composer': string;
  'composerContainer': string;
  'handoffAssigned': string;
  'selected': string;
  'sendButton': string;
  'shortcutDropdown': string;
  'shortcutItem': string;
  'shortcutKey': string;
  'shortcutListItem': string;
  'shortcutValue': string;
}
declare var cssExports: CssExports;
export = cssExports;
