export const MODULE_NAME = 'hitlnext'
export const WEBSOCKET_TOPIC = 'hitlnext'
export const HANDOFF_TABLE_NAME = 'handoffs'
export const COMMENT_TABLE_NAME = 'comments'
export const ASSIGNMENT_HISTORY_TABLE_NAME = 'assignment_history'
