// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  '_-1': string;
  '_0': string;
  '_1': string;
  '_2': string;
  '_3': string;
  '_4': string;
  'card': string;
  'card_body': string;
  'card_text': string;
  'card_title': string;
  'centered_container': string;
  'form_wrapper': string;
  'homepage': string;
  'inner': string;
  'label_input': string;
  'linea_vertical': string;
  'login_box': string;
  'login_btn': string;
  'login_btn_tgc': string;
  'login_subtitle': string;
  'logo': string;
  'middle': string;
  'strenghtLabel': string;
  'strengthDetails': string;
  'strengthProgress': string;
  'tgc_login_img': string;
  'tgc_logo_wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
