// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addTagButton': string;
  'categoryActions': string;
  'categoryCard': string;
  'categoryColor': string;
  'categoryHeader': string;
  'categoryName': string;
  'categoryTitle': string;
  'chevron': string;
  'chevronExpanded': string;
  'container': string;
  'dialogActions': string;
  'emptyIcon': string;
  'emptyState': string;
  'formGroup': string;
  'formLabel': string;
  'header': string;
  'pageInfo': string;
  'pagination': string;
  'tagDescription': string;
  'tagItem': string;
  'tagList': string;
  'tagManagement': string;
  'tagName': string;
  'title': string;
}
declare var cssExports: CssExports;
export = cssExports;
